site_name: 知识产权政策

nav:
  - 政策导航: index.md
  - 国家级:
    - 二十大报告: 国家级/二十大报告.md
    - 知识产权强国建设纲要(2021—2035年): 国家级/知识产权强国建设纲要(2021—2035年).md
    - 国务院关于印发“十四五”国家知识产权保护和运用规划的通知: 国家级/国务院关于印发“十四五”国家知识产权保护和运用规划的通知.md
    - 知识产权人才“十四五”规划: 国家级/知识产权人才“十四五”规划.md
    - 知识产权公共服务“十四五”规划: 国家级/知识产权公共服务“十四五”规划.md
    - 关于保护种业知识产权打击假冒伪劣套牌侵权营造种业振兴良好环境的指导意见: 国家级/关于保护种业知识产权打击假冒伪劣套牌侵权营造种业振兴良好环境的指导意见.md
    - 2023年知识产权强国建设纲要和“十四五”规划实施推进计划: 国家级/2023年知识产权强国建设纲要和“十四五”规划实施推进计划.md
    - 专利转化运用专项行动方案(2023—2025年): 国家级/专利转化运用专项行动方案(2023—2025年).md
    - 高校和科研机构存量专利盘活工作方案: 国家级/高校和科研机构存量专利盘活工作方案.md
    - 专利产业化促进中小企业成长计划实施方案: 国家级/专利产业化促进中小企业成长计划实施方案.md
    - 推动知识产权高质量发展年度工作指引(2024): 国家级/推动知识产权高质量发展年度工作指引(2024).md
    - 深化协同保护加强知识产权法治保障的意见: 国家级/深化协同保护加强知识产权法治保障的意见.md
    - 关于推进重点产业知识产权强链增效的若干措施: 国家级/关于推进重点产业知识产权强链增效的若干措施.md
    - 中共中央关于进一步全面深化改革、推进中国式现代化的决定: 国家级/中共中央关于进一步全面深化改革、推进中国式现代化的决定.md
    - 全面提升知识产权公共服务效能的指导意见: 国家级/全面提升知识产权公共服务效能的指导意见.md
    - 2023年中央经济工作会议: 国家级/2023年中央经济工作会议.md
    - 关于促进民营经济发展壮大的意见: 国家级/关于促进民营经济发展壮大的意见.md
    - 习近平主持召开进一步推动长江经济带高质量发展座谈会: 国家级/习近平主持召开进一步推动长江经济带高质量发展座谈会.md
    - 关于加强煤炭清洁高效利用的意见(发改运行〔2024〕1345号): 国家级/关于加强煤炭清洁高效利用的意见(发改运行〔2024〕1345号).md


  - 江苏省:
    - 江苏省知识产权强省建设纲要(2021-2035年): 江苏省/江苏省知识产权强省建设纲要(2021-2035年).md
    - 江苏省“十四五”知识产权发展规划: 江苏省/江苏省“十四五”知识产权发展规划.md
    - 江苏省“十四五”新能源汽车产业发展规划: 江苏省/江苏省“十四五”新能源汽车产业发展规划.md
    - 苏南国家自主创新示范区一体化发展实施方案(2020－2022年)的通知: 江苏省/苏南国家自主创新示范区一体化发展实施方案(2020－2022年)的通知.md
    - 江苏省“十四五”科技创新规划的通知: 江苏省/江苏省“十四五”科技创新规划的通知.md
    - 支持江苏南京国家农业高新技术产业示范区高质量发展的若干意见: 江苏省/支持江苏南京国家农业高新技术产业示范区高质量发展的若干意见.md
    - 加快工业软件自主创新若干政策措施的通知: 江苏省/加快工业软件自主创新若干政策措施的通知.md
    - 江苏省专利转化运用专项行动实施方案的通知: 江苏省/江苏省专利转化运用专项行动实施方案的通知.md
    - 江苏省数据知识产权登记管理办法(试行)的通知: 江苏省/江苏省数据知识产权登记管理办法(试行)的通知.md
    - 关于高标准推进知识产权强省建设若干政策措施的通知: 江苏省/关于高标准推进知识产权强省建设若干政策措施的通知.md


  - 浙江省:
    - 深化数据知识产权改革推动高质量发展的意见: 浙江省/深化数据知识产权改革推动高质量发展的意见.md
    - 深入实施知识产权人才集聚行动打造知识产权人才高地的意见: 浙江省/深入实施知识产权人才集聚行动打造知识产权人才高地的意见.md
    - 关于贯彻专利转化运用专项行动方案(2023—2025年)的实施意见: 浙江省/关于贯彻专利转化运用专项行动方案(2023—2025年)的实施意见.md
    - 浙江省知识产权保护和促进条例: 浙江省/浙江省知识产权保护和促进条例.md



  - 广东省:
    - 广东省专利转化运用专项行动实施方案: 广东省/广东省专利转化运用专项行动实施方案.md
    - 广东省推动专精特新企业高质量发展指导意见的通知: 广东省/广东省推动专精特新企业高质量发展指导意见的通知.md
    - 广东省关于人工智能赋能千行百业若干措施的通知: 广东省/广东省关于人工智能赋能千行百业若干措施的通知.md
    - 广东省知识产权公共服务普惠工程实施计划(2023—2025年): 广东省/广东省知识产权公共服务普惠工程实施计划(2023—2025年).md
    - 广东省“十四五”文物保护和科技创新实施方案的通知: 广东省/广东省“十四五”文物保护和科技创新实施方案的通知.md
    - 广东省知识产权保护条例: 广东省/广东省知识产权保护条例.md
    - 广东省科学技术奖励办法: 广东省/广东省科学技术奖励办法.md
    - 加快培育发展未来产业行动方案的通知: 广东省/加快培育发展未来产业行动方案的通知.md
    - 广东省知识产权领域省级与市县财政事权和支出责任划分改革方案: 广东省/广东省知识产权领域省级与市县财政事权和支出责任划分改革方案.md




  - 上海市:
    - 上海市知识产权保护和运用“十四五”规划: 上海市/上海市知识产权保护和运用“十四五”规划.md
    - 上海市知识产权强市建设纲要(2021—2035年): 上海市/上海市知识产权强市建设纲要(2021—2035年).md
    - 上海市专利转化运用专项行动实施方案: 上海市/上海市专利转化运用专项行动实施方案.md
    - 上海市知识产权局2024年知识产权代理行业“蓝天”行动实施方案: 上海市/上海市知识产权局2024年知识产权代理行业“蓝天”行动实施方案.md
    - 关于加强本市知识产权鉴定工作的暂行实施办法: 上海市/关于加强本市知识产权鉴定工作的暂行实施办法.md


  - 北京市:
    - 北京市“十四五”时期知识产权发展规划: 北京市/北京市“十四五”时期知识产权发展规划.md
    - 北京市产业知识产权促进中心认定与管理办法: 北京市/北京市产业知识产权促进中心认定与管理办法.md
    - 加强北京市农林业知识产权工作的指导意见: 北京市/加强北京市农林业知识产权工作的指导意见.md
    - 关于进一步加强北京市知识产权公共服务的意见: 北京市/关于进一步加强北京市知识产权公共服务的意见.md
    - 关于加强北京市旅游产业知识产权工作的指导意见: 北京市/关于加强北京市旅游产业知识产权工作的指导意见.md


# 主题
theme:
  name: material
  features:
    - instant
    - navigation.tabs
    - navigation.sections
  palette:
    primary: '#663366'
    accent: '#663366'

# 文本扩展
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true


# 额外的js
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js

# 额外的css
extra_css:
  - css/extra.css # 确保路径正确
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css

# 额外的插件
extra:
  mathjax:
    tex:
      tags: 'ams'  # 启用 AMS 标签支持
      processEscapes: true

# 插件
plugins:
  - search